### ISSUE TITLE
polars.exceptions.InvalidOperationError: file encoding is not UTF-8

### ISSUE THREAD

**Issue by Holthuizen** [ifnesi/1brc#12]
I first ran `pip install -r requirements.txt` in a new .venv
but when running `python createMeasurements.py` i get the following error:

![image](https://github.com/user-attachments/assets/703cc566-c84a-464c-aef2-b8f2b86ee1ab)
Traceback (most recent call last):
  File "D:\CodingProjecs\Python\1brc\createMeasurements.py", line 507, in <module>
    measurement.generate_measurement_file(
  File "D:\CodingProjecs\Python\1brc\createMeasurements.py", line 463, in generate_measurement_file
    data.write_csv(f, separator=sep, float_precision=1, include_header=False)
  File "D:\CodingProjecs\Python\1brc\.venv\Lib\site-packages\polars\dataframe\frame.py", line 2719, in write_csv
    self._df.write_csv(
polars.exceptions.InvalidOperationError: file encoding is not UTF-8

**Comment by ifnesi** [comment]
Hi @Holthuizen, thank you. Please pull the latest commit and try again. There were a PR open to fix that and I didn't merge it until now. The problem was when opening the measurement file to write to it the encoding was not set to UTF-8.
